// Sparky's Tip of the Day — 50 tips sourced from electrician forums, inspection data, and field experience

export interface SparkTip {
  id: string
  category: 'safety' | 'code' | 'technique' | 'tool'
  title: string
  body: string
  reference?: string
}

export const TIPS: SparkTip[] = [
  {
    id: 'tip-01',
    category: 'code',
    title: 'Voltage Drop Rule of Thumb',
    body: 'NEC recommends no more than 3% voltage drop on branch circuits and 5% total for feeder + branch combined. Always calculate before pulling wire on runs over 50 feet.',
    reference: 'NEC 210.19(A) Informational Note',
  },
  {
    id: 'tip-02',
    category: 'safety',
    title: 'Lockout/Tagout Every Single Time',
    body: 'Never trust someone who says "it\'s already off." Verify zero energy state yourself, every time. The one time you skip it is the one time it bites you.',
    reference: 'NFPA 70E 120.5',
  },
  {
    id: 'tip-03',
    category: 'technique',
    title: 'Anti-Short Bushings Are Not Optional',
    body: 'Red anti-short bushings on MC cable protect conductors from armor edges at connectors. Inspectors catch missing bushings constantly — it\'s one of the top residential failures.',
    reference: 'NEC 330.40',
  },
  {
    id: 'tip-04',
    category: 'code',
    title: 'Box Fill: Don\'t Forget the Clamps',
    body: 'Internal cable clamps count as one conductor volume based on the largest wire in the box. Crowded conductor boxes are the #1 NEC violation reported by inspectors nationwide.',
    reference: 'NEC 314.16(B)(2)',
  },
  {
    id: 'tip-05',
    category: 'tool',
    title: 'Level on Every Bend',
    body: 'Keep a torpedo level on your bender shoe. A level conduit run starts with level bends. 30 seconds checking saves hours of rework and keeps inspectors happy.',
  },
  {
    id: 'tip-06',
    category: 'safety',
    title: 'The GFCI 6-Foot Rule',
    body: 'Any 125V–250V receptacle within 6 feet of a sink edge needs GFCI protection. Measure from the outside edge of the sink — not the faucet, not the counter edge.',
    reference: 'NEC 210.8',
  },
  {
    id: 'tip-07',
    category: 'technique',
    title: '30-Degree Offset Math',
    body: 'For 30° offsets: multiply the obstacle height by 2 for distance between bends. Shrinkage is 3/16" per inch of rise. Most common bend angle for a reason — learn it cold.',
  },
  {
    id: 'tip-08',
    category: 'code',
    title: 'Terminal Temperature Ratings',
    body: 'Even if your wire is rated 90°C, most terminals are rated 75°C. You must use the 75°C ampacity column unless the equipment is specifically listed for higher temp.',
    reference: 'NEC 110.14(C)',
  },
  {
    id: 'tip-09',
    category: 'code',
    title: 'Conduit Fill: The 40% Rule',
    body: '3+ conductors in a conduit = 40% max fill. 2 conductors = 31%. 1 conductor = 53%. These are cross-sectional area percentages. Use Chapter 9 tables, not guesswork.',
    reference: 'NEC Chapter 9, Table 1',
  },
  {
    id: 'tip-10',
    category: 'safety',
    title: 'Know Your Arc Flash Boundaries',
    body: 'Before opening any energized panel, identify the arc flash boundary. The prohibited approach boundary is where serious burns happen in under one second. Label it and respect it.',
    reference: 'NFPA 70E Table 130.7(C)(15)',
  },
  {
    id: 'tip-11',
    category: 'code',
    title: 'AFCI vs. GFCI — Know the Difference',
    body: 'GFCI protects people from shock (ground faults to ground). AFCI protects property from arc-fault fires. Many locations now require dual-function breakers. Don\'t mix them up on a rough-in.',
    reference: 'NEC 210.8 & 210.12',
  },
  {
    id: 'tip-12',
    category: 'technique',
    title: 'Pull Wire — Don\'t Push It',
    body: 'Always pull wire with a fish tape and proper head. Pushing creates kinks and jacket damage. Use wire-pulling lubricant on runs over 50 feet. Dry lube ruins future pulls.',
  },
  {
    id: 'tip-13',
    category: 'code',
    title: 'Panel Labeling Is Code, Not Optional',
    body: 'Every circuit must be clearly labeled in a way non-electricians can understand. No shorthand, no trade symbols. Inspectors fail panels for this constantly. Do it right the first time.',
    reference: 'NEC 408.4',
  },
  {
    id: 'tip-14',
    category: 'technique',
    title: 'Repair Kinked Fish Tape with Nails',
    body: 'Drive 8–10 nails in a straight line in a block of wood, 3/4" apart. Weave the kinked tape through and pull. Repeat until straight. Saves buying a new one.',
  },
  {
    id: 'tip-15',
    category: 'safety',
    title: 'Left Hand in Your Pocket on Live Work',
    body: 'When working on energized equipment, keep your left hand in your pocket or behind your back. Current crossing chest is what stops hearts. One-hand rule is real field practice.',
    reference: 'NFPA 70E',
  },
  {
    id: 'tip-16',
    category: 'code',
    title: 'Nail Plates Are Not Suggestions',
    body: 'If a hole edge is within 1-1/4" of the face of framing, a nail plate is required. Missing nail plates are one of the most cited framing-stage violations. Run out of plates? Stop and get more.',
    reference: 'NEC 300.4(A)(1)',
  },
  {
    id: 'tip-17',
    category: 'technique',
    title: 'PVC Bending: Make an EMT Template First',
    body: 'When making production PVC bends, bend an EMT template first. Then use it as a form when the PVC comes out of the hot box. Every bend will match exactly.',
  },
  {
    id: 'tip-18',
    category: 'code',
    title: 'Splice in a Box — Every Time',
    body: 'All splices must be in a covered junction box. Open splices outside of boxes are one of the most cited commercial violations. No exceptions, no "it\'s in the ceiling" excuses.',
    reference: 'NEC 300.15',
  },
  {
    id: 'tip-19',
    category: 'safety',
    title: 'Never Assume the Other Guy Turned It Off',
    body: 'The most dangerous words in the trade are "someone already locked it out." Test before you touch, every time. Non-contact testers are $20 — use them.',
  },
  {
    id: 'tip-20',
    category: 'technique',
    title: 'Two-Man Wire Pull Signals',
    body: 'When pulling wire and you can\'t hear each other: 1 tug = stop, 2 tugs = go, 3 tugs = we\'re done. Agree on signals before you start. Saves a lot of yelling and damaged wire.',
  },
  {
    id: 'tip-21',
    category: 'code',
    title: 'Derating: More Than 3 Conductors',
    body: 'More than 3 current-carrying conductors in a raceway requires ampacity derating. 4–6 conductors = 80%. 7–9 = 70%. Forgetting to derate is a top inspection failure on commercial work.',
    reference: 'NEC 310.15(C)(1), Table 310.15(C)(1)',
  },
  {
    id: 'tip-22',
    category: 'tool',
    title: 'Anti-Itch Remedy for Insulation Work',
    body: 'Before working in fiberglass insulation, coat your arms, neck, and face with baby powder or cornstarch. The powder fills the skin\'s pores so fibers can\'t get in. Works better than long sleeves alone.',
  },
  {
    id: 'tip-23',
    category: 'code',
    title: 'Wire Size and Breaker Must Match',
    body: 'A common DIY disaster: #14 wire on a 20A breaker. The wire is the protection, not the breaker. Wrong breaker = overheating wire = fire. Match wire size to breaker per NEC Table 310.12.',
    reference: 'NEC 240.4',
  },
  {
    id: 'tip-24',
    category: 'technique',
    title: 'Mark Your Conduit Twice, Bend Once',
    body: 'Double-check every measurement and mark before you bend. There\'s no clean way to un-bend conduit. The extra 10 seconds saves a 10-foot stick of rigid.',
  },
  {
    id: 'tip-25',
    category: 'code',
    title: 'GFCI Must Be Readily Accessible',
    body: 'GFCIs installed behind appliances or in hard-to-reach locations violate code. They must be accessible so users can reset them. Inspector tip: if you can\'t reach it standing in front of it, move it.',
    reference: 'NEC 210.8',
  },
  {
    id: 'tip-26',
    category: 'safety',
    title: 'Drill Through Floor Joists? Check Both Sides',
    body: 'Before drilling through a floor joist, check what\'s on the other side. Plumbing, low-voltage, and existing circuits hide there. A slow bit through a gas line ends careers.',
  },
  {
    id: 'tip-27',
    category: 'code',
    title: 'Bonding at Service Equipment',
    body: 'Install a bonding fitting where conduit enters through intact knockouts at service equipment. Missing this bond is a common service-entrance violation that creates shock hazards.',
    reference: 'NEC 250.92(B)',
  },
  {
    id: 'tip-28',
    category: 'technique',
    title: 'Watts-to-Amps Shortcut',
    body: 'Multiply watts by the reciprocal of voltage instead of dividing: 120V = 0.00833, 208V = 0.00481, 240V = 0.00417, 277V = 0.00361, 480V = 0.00208. Faster in your head on the job.',
  },
  {
    id: 'tip-29',
    category: 'code',
    title: 'Don\'t Close Up Before Inspection',
    body: 'Never close walls, pour concrete, or bury conduit before the inspector has signed off. Having to rip open drywall is expensive and embarrassing. This is one of the top inspection violations.',
  },
  {
    id: 'tip-30',
    category: 'safety',
    title: 'Wear Eye Protection — Every Day',
    body: 'You only get two eyes. Wear safety glasses every day, not just when it feels dangerous. The splatter from a drill, a wire whipping back, or a blown fuse doesn\'t announce itself.',
  },
  {
    id: 'tip-31',
    category: 'code',
    title: 'MC Cable in Accessible Ceilings',
    body: 'NM cable above accessible (drop tile) ceilings in commercial spaces is a common code violation. MC cable is required in those spaces. Know the occupancy type before you start pulling.',
    reference: 'NEC 334.10, 334.12',
  },
  {
    id: 'tip-32',
    category: 'technique',
    title: 'Label Wires at Both Ends',
    body: 'Mark every conductor at both ends when pulling. Use the same label, same numbering. You will not remember what goes where when you come back six months later for a service call.',
  },
  {
    id: 'tip-33',
    category: 'code',
    title: 'Working Space Around Panels',
    body: '30" wide minimum, 3 feet deep (for 0–150V to ground), 6\'6\" headroom. That means no shelves, no pipes, no equipment in the working space. Facilities management always tries to violate this.',
    reference: 'NEC 110.26',
  },
  {
    id: 'tip-34',
    category: 'safety',
    title: 'Always Torque Your Lugs',
    body: 'Under-torqued lugs are a leading cause of panel fires. Use a torque screwdriver and follow the torque spec on the label inside every panel door. It\'s there for a reason.',
    reference: 'NEC 110.14(D)',
  },
  {
    id: 'tip-35',
    category: 'technique',
    title: 'Make Holes in Drywall with EMT',
    body: 'Need to punch a lot of drywall holes for toggle bolts? Use a 10"–18" piece of 1/2" or 3/4" EMT. Tap it through the drywall. Clean, fast, no special bits needed.',
  },
  {
    id: 'tip-36',
    category: 'code',
    title: 'GEC Armor Bonding',
    body: 'Bond every end of the armor that protects the grounding electrode conductor. Missing this bond is a top-cited service violation. The armor has to be bonded so it doesn\'t restrict the GEC.',
    reference: 'NEC 250.64(E)',
  },
  {
    id: 'tip-37',
    category: 'code',
    title: 'Motor Wire: 125% Rule',
    body: 'Motor branch circuit conductors must be sized at 125% of motor FLA, not 100%. Undersized motor wire is a common violation. Use NEC 430.248/250 FLA tables, not nameplate alone.',
    reference: 'NEC 430.22',
  },
  {
    id: 'tip-38',
    category: 'technique',
    title: 'Always Verify with the AHJ First',
    body: 'Codes are national, but interpretations vary by city and inspector. A 5-minute call to the Authority Having Jurisdiction before a job prevents rework. Ask what they want to see, then do it.',
  },
  {
    id: 'tip-39',
    category: 'safety',
    title: 'Treat Every Wire as Live Until Proven Dead',
    body: 'In existing buildings especially, what\'s labeled "off" often isn\'t. Always test with a non-contact voltage tester before cutting, splicing, or terminating. Old wiring can be full of surprises.',
  },
  {
    id: 'tip-40',
    category: 'code',
    title: 'Remove Abandoned Cables',
    body: 'Accessible abandoned low-voltage cables must be removed unless tagged for future use. Leaving old cables in ceilings and walls violates code and creates fire risks. Inspectors are looking for this now.',
    reference: 'NEC 800.25',
  },
  {
    id: 'tip-41',
    category: 'technique',
    title: 'Read the NEC for What You\'re Doing Now',
    body: 'Don\'t try to read the NEC cover to cover. Instead, look up the article that covers your current task after work. Running MC all day? Read Article 330 tonight. This is how journeymen learn it cold.',
  },
  {
    id: 'tip-42',
    category: 'code',
    title: 'Breaker Compatibility Matters',
    body: 'Never install a breaker that isn\'t listed for the specific panel brand. "Fits" is not the same as "listed." Cross-brand breakers in panels void the listing and create fire hazards.',
    reference: 'NEC 110.3(B)',
  },
  {
    id: 'tip-43',
    category: 'safety',
    title: 'One-Conductor Rule on Live Circuits',
    body: 'Only one hand on a live circuit at a time. Never let both hands contact different parts of an energized circuit simultaneously. This is the field rule that keeps journeymen alive.',
  },
  {
    id: 'tip-44',
    category: 'technique',
    title: 'Photo Everything Before Close-Up',
    body: 'Take photos of every rough-in before drywall closes up. Inspectors can\'t see through walls. Photos prove your work and resolve disputes quickly. Store them per job in your phone.',
  },
  {
    id: 'tip-45',
    category: 'code',
    title: 'Different Wire Sizes on the Same Lug',
    body: 'Putting two different gauge wires under one lug is a code violation unless the lug is listed for that combination. Common in sub-panels by non-electricians. Flag it and fix it.',
    reference: 'NEC 110.14',
  },
  {
    id: 'tip-46',
    category: 'tool',
    title: 'Buy Tools Every Payday',
    body: 'Even if it\'s just one quality screwdriver or a pair of Klein strippers, buy a tool every payday when you\'re starting out. Tradesmen who use garbage tools do garbage work. Quality tools pay you back.',
  },
  {
    id: 'tip-47',
    category: 'code',
    title: 'Open Breaker Spaces Need Knockouts',
    body: 'Unused breaker spaces in a panel must be covered. Open gaps expose live bus bars and create shock and flash hazards. It\'s a cheap fix and inspectors always check.',
    reference: 'NEC 408.7',
  },
  {
    id: 'tip-48',
    category: 'technique',
    title: 'Verify What Others Call "Code" in the Book',
    body: 'When a journeyman or foreman tells you something is code, go look it up. You\'ll be surprised how often what gets passed down as "code" isn\'t actually in the NEC. Know the difference.',
  },
  {
    id: 'tip-49',
    category: 'code',
    title: 'Wiring Must Be Supported and Secured',
    body: 'NM cable sags, MC drooping across the ceiling, unsupported conduit — all violations. Support intervals are in the code for every wiring method. Sagging wiring is the first thing an inspector notices.',
    reference: 'NEC 330.30, 336.30, 358.30',
  },
  {
    id: 'tip-50',
    category: 'safety',
    title: 'Stock the Truck After Every Use',
    body: 'Restock materials and supplies on the truck at the end of every day or after each use. Running back to the shop mid-job because you\'re out of connectors wastes your time and your foreman\'s patience.',
  },
]

export function getTipOfTheDay(): SparkTip {
  // Random tip on every call
  return TIPS[Math.floor(Math.random() * TIPS.length)]
}
